// <auto-generated />
namespace Dog_Seller.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addDogToDb : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addDogToDb));
        
        string IMigrationMetadata.Id
        {
            get { return "202006030859044_addDogToDb"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
